name: video_transcription
services:
  video-download:
    build:
      context: .
      dockerfile: Dockerfile.video-download
    container_name: video-download
    volumes:
      - /volume1/docker/careerlearning/transcription/videos:/data/videos
      - /volume1/docker/careerlearning/transcription/tracking:/data/tracking
    environment:
      - PYTHONUNBUFFERED=1
      - DOWNLOAD_DIR=/data/videos
      - TRACKING_DIR=/data/tracking
      - SERVICE_NAME=video-download
    healthcheck:
      test: ["CMD", "python", "-c", "import os; assert os.path.exists('/data/videos')"]
      interval: 30s
      timeout: 30s
      retries: 3
      start_period: 5s

  transcription:
    build:
      context: .
      dockerfile: Dockerfile.transcribe
    container_name: transcription
    volumes:
      - /volume1/docker/careerlearning/transcription/videos:/data/videos
      - /volume1/docker/careerlearning/transcription/transcripts:/data/transcripts
      - /volume1/docker/careerlearning/transcription/tracking:/data/tracking
    environment:
      - PYTHONUNBUFFERED=1
      - DOWNLOAD_DIR=/data/videos
      - TRANSCRIPT_DIR=/data/transcripts
      - TRACKING_DIR=/data/tracking
      - WHISPER_MODEL=base
      - SERVICE_NAME=transcription
    healthcheck:
      test: ["CMD", "python", "-c", "import os; assert os.path.exists('/data/videos') and os.path.exists('/data/transcripts')"]
      interval: 30s
      timeout: 30s
      retries: 3
      start_period: 5s 